[package]
name = "blockchainCertificate"
version = "1.0.0"
authors = []

[addresses]
blockchainCertificate = '0x9769606b8e52b3b75fdf54166addbef39eeec101e11cc272580a4766e46ac3ec'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-1.0"  # Use a known working release tag, branch, or commit hash

[dev-dependencies]

